# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build, tag and release

on:
  push:
    branches: [master]
    
env:
  NODE_VERSION: 14.x

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'version bump to') || !contains(github.event.head_commit.message, 'skip ci')"
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: npm ci
    - run: npm run test
    - run: npm run build --if--present


  build:
    needs: [test]
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      tag: ${{ steps.tag_name.outputs.TAG }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: npm ci
    - run: npm run build
    - name: Automated Version Bump
      uses: phips28/gh-action-bump-version@master
    - name: Export TAG Parameter
      id: tag_name
      run: |
        echo ::set-output name=TAG::`cat package.json | jq -r .version`
      shell: bash


  realease:
    needs: [build]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: GH Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v${{ needs.build.outputs.tag }}"
