name: Test on pull
on:
  pull_request:
    branches: [ master ]

env:
  NODE_VERSION: 20.x

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: npm ci
    - run: npm run test
    - run: npm run build --if--present
    
  
